import base64
import os
import uuid
from pathlib import Path
from typing import Dict, List, Optional

import httpx
import yaml
from fastapi import FastAPI, File, HTTPException, UploadFile
from fastapi.responses import FileResponse, HTMLResponse
from pydantic import BaseModel, Field

# ── configuration ──────────────────────────────────────────────────────────────
_HERE = Path(__file__).parent
_PKG = _HERE.parent  # .../ar_audio/

POINTS_FILE = Path(os.environ.get(
    "AR_POINTS_FILE",
    str(_PKG / "config" / "ar_points.yaml"),
))
AUDIO_BASE = Path(os.environ.get(
    "AUDIO_BASE_PATH",
    str(_PKG / "audio"),
))
GOOGLE_TTS_KEY = os.environ.get("GOOGLE_TTS_KEY", "")

AUDIO_BASE.mkdir(parents=True, exist_ok=True)

# ── models ─────────────────────────────────────────────────────────────────────

class ARPointIn(BaseModel):
    name: str
    latitude: float
    longitude: float
    audio_file: Optional[str] = None
    radius: float = 10.0
    tts_texts: Dict[str, str] = Field(default_factory=dict)
    audio_files: Dict[str, str] = Field(default_factory=dict)


# ── YAML helpers ───────────────────────────────────────────────────────────────

def _load() -> List[dict]:
    if not POINTS_FILE.exists():
        return []
    with open(POINTS_FILE, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f) or {}
    pts = data.get("ar_points", [])
    dirty = False
    for p in pts:
        if not p.get("id"):
            p["id"] = uuid.uuid4().hex[:8]
            dirty = True
    if dirty:
        _save(pts)
    return pts


def _save(pts: List[dict]) -> None:
    POINTS_FILE.parent.mkdir(parents=True, exist_ok=True)
    with open(POINTS_FILE, "w", encoding="utf-8") as f:
        yaml.dump(
            {"ar_points": pts},
            f,
            allow_unicode=True,
            default_flow_style=False,
            sort_keys=False,
        )


# ── FastAPI app ────────────────────────────────────────────────────────────────

app = FastAPI(title="AR Audio Admin", version="1.0.0")


@app.get("/", response_class=HTMLResponse)
async def root():
    return (_HERE / "static" / "index.html").read_text(encoding="utf-8")


@app.get("/api/points")
async def get_points():
    return _load()


@app.post("/api/points", status_code=201)
async def create_point(body: ARPointIn):
    pts = _load()
    d = body.model_dump()
    d["id"] = uuid.uuid4().hex[:8]
    pts.append(d)
    _save(pts)
    return d


@app.put("/api/points/{pid}")
async def update_point(pid: str, body: ARPointIn):
    pts = _load()
    for i, p in enumerate(pts):
        if p.get("id") == pid:
            d = body.model_dump()
            d["id"] = pid
            # preserve audio_files generated by TTS if client sends empty dict
            if not d.get("audio_files"):
                d["audio_files"] = p.get("audio_files", {})
            pts[i] = d
            _save(pts)
            return d
    raise HTTPException(404, "Point not found")


@app.delete("/api/points/{pid}")
async def delete_point(pid: str):
    pts = _load()
    new_pts = [p for p in pts if p.get("id") != pid]
    if len(new_pts) == len(pts):
        raise HTTPException(404, "Point not found")
    _save(new_pts)
    return {"ok": True}


_LANG_CODES: Dict[str, tuple] = {
    "ja": ("ja-JP", "NEUTRAL"),
    "en": ("en-US", "NEUTRAL"),
    "zh": ("zh-CN", "NEUTRAL"),
}


@app.post("/api/points/{pid}/tts")
async def generate_tts(pid: str, lang: str = "ja"):
    if not GOOGLE_TTS_KEY:
        raise HTTPException(500, "GOOGLE_TTS_KEY is not configured")
    if lang not in _LANG_CODES:
        raise HTTPException(400, f"lang must be one of {list(_LANG_CODES)}")

    pts = _load()
    idx = next((i for i, p in enumerate(pts) if p.get("id") == pid), None)
    if idx is None:
        raise HTTPException(404, "Point not found")

    text = (pts[idx].get("tts_texts") or {}).get(lang, "").strip()
    if not text:
        raise HTTPException(400, f"tts_texts.{lang} is empty")

    lc, gender = _LANG_CODES[lang]
    url = f"https://texttospeech.googleapis.com/v1/text:synthesize?key={GOOGLE_TTS_KEY}"
    async with httpx.AsyncClient(timeout=30) as client:
        r = await client.post(url, json={
            "input": {"text": text},
            "voice": {"languageCode": lc, "ssmlGender": gender},
            "audioConfig": {"audioEncoding": "MP3"},
        })
    if r.status_code != 200:
        raise HTTPException(502, f"Google TTS API error: {r.text[:400]}")

    audio = base64.b64decode(r.json()["audioContent"])
    fname = f"{pid}_{lang}.mp3"
    (AUDIO_BASE / fname).write_bytes(audio)

    pts[idx].setdefault("audio_files", {})[lang] = fname
    if not pts[idx].get("audio_file"):
        pts[idx]["audio_file"] = fname
    _save(pts)
    return {"filename": fname, "bytes": len(audio)}


@app.post("/api/points/{pid}/upload")
async def upload_audio(pid: str, file: UploadFile = File(...)):
    pts = _load()
    idx = next((i for i, p in enumerate(pts) if p.get("id") == pid), None)
    if idx is None:
        raise HTTPException(404, "Point not found")

    ext = Path(file.filename).suffix.lower() if file.filename else ".mp3"
    fname = f"{pid}{ext}"
    (AUDIO_BASE / fname).write_bytes(await file.read())

    pts[idx]["audio_file"] = fname
    _save(pts)
    return {"filename": fname}


@app.post("/api/points/{pid}/set_active_audio")
async def set_active_audio(pid: str, filename: str):
    pts = _load()
    idx = next((i for i, p in enumerate(pts) if p.get("id") == pid), None)
    if idx is None:
        raise HTTPException(404, "Point not found")
    pts[idx]["audio_file"] = filename
    _save(pts)
    return {"ok": True}


@app.get("/audio/{filename}")
async def serve_audio(filename: str):
    # prevent path traversal
    if "/" in filename or "\\" in filename or ".." in filename:
        raise HTTPException(400, "Invalid filename")
    path = AUDIO_BASE / filename
    if not path.exists():
        raise HTTPException(404, "Audio file not found")
    return FileResponse(str(path))


# ── entry point ────────────────────────────────────────────────────────────────

def main():
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8080)


if __name__ == "__main__":
    main()
